server:
  port: 9100

spring:
  application:
    name: auth-service

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey

