spring:
  application:
    name: api-gateway

server:
  port: 8762

zuul:
  routes:
    auth-service:
      path: /auth/**
      url: http://127.0.0.1:9100/
      sensitiveHeaders: Cookie, Set-Cookie
      stripPrefix: false
    user-service:
      path: /api/user-service/**
      url: http://127.0.0.1:8081/
security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey

